### ISSUE TITLE
Setup Kanban-Board

### ISSUE THREAD

**Issue by monika-soam** [monika-soam/kanban-board#21]
**For the reviewer**

- We are a team of 2 people
- Adrian- Student A
- Monika- Student B

Below is the link of our project

`https://github.com/monika-soam/kanban-board/projects/1`

**Comment by brytebee** [comment]
Hi Team👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- You have correctly stated the team number✔️
- You have a link to the project✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
- [x] **Required:** Kindly remove 5 cards from the Kanban that belongs to the 3rd student except if going forward you are committing to doing them.
- [x] **Required:** Assigned each card to a team member. You should see a circle with the user's avatar on each card.
![image](https://user-images.githubusercontent.com/27709832/162767168-44b299ec-623a-48db-a4c3-22005fe56920.png)
- [x] **Required:** Cards should be assigned fairly and equally.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by monika-soam** [comment]
Thank you for your review, I have done all the required changes.
